export const STATE_LIST = [
    { id: 1, name: "Andaman and Nicobar Islands", code: "AN" },
    { id: 2, name: "Andhra Pradesh", code: "AP" },
    { id: 3, name: "Arunachal Pradesh", code: "AR" },
    { id: 4, name: "Assam", code: "AS" },
    { id: 5, name: "Bihar", code: "BR" },
    { id: 6, name: "Chandigarh", code: "CH" },
    { id: 7, name: "Chhattisgarh", code: "CT" },
    { id: 8, name: "Dadra and Nagar Haveli", code: "DN" },
    { id: 9, name: "Daman and Diu", code: "DD" },
    { id: 10, name: "Delhi", code: "DL" },
    { id: 11, name: "Goa", code: "GA" },
    { id: 12, name: "Gujarat", code: "GJ" },
    { id: 13, name: "Haryana", code: "HR" },
    { id: 14, name: "Himachal Pradesh", code: "HP" },
    { id: 15, name: "Jammu and Kashmir", code: "JK" },
    { id: 16, name: "Jharkhand", code: "JH" },
    { id: 17, name: "Karnataka", code: "KA" },
    { id: 18, name: "Kerala", code: "KL" },
    { id: 19, name: "Ladakh", code: "LA" },
    { id: 20, name: "Lakshadweep", code: "LD" },
    { id: 21, name: "Madhya Pradesh", code: "MP" },
    { id: 22, name: "Maharashtra", code: "MH" },
    { id: 23, name: "Manipur", code: "MN" },
    { id: 24, name: "Meghalaya", code: "ML" },
    { id: 25, name: "Mizoram", code: "MZ" },
    { id: 26, name: "Nagaland", code: "NL" },
    { id: 27, name: "Odisha", code: "OR" },
    { id: 28, name: "Puducherry", code: "PY" },
    { id: 29, name: "Punjab", code: "PB" },
    { id: 30, name: "Rajasthan", code: "RJ" },
    { id: 31, name: "Sikkim", code: "SK" },
    { id: 32, name: "Tamil Nadu", code: "TN" },
    { id: 33, name: "Telangana", code: "TS" },
    { id: 34, name: "Tripura", code: "TR" },
    { id: 35, name: "Uttar Pradesh", code: "UP" },
    { id: 36, name: "Uttarakhand", code: "UK" },
    { id: 37, name: "West Bengal", code: "WB" }
  ];
  